// Level layout definitions
export const levels = [
    [ /* Level 0 data */
        "                 ",
        "                 ",
        "                 ",
        "wwwwwhwwwwwwwwwwww",
        "whhhh     hhhhh w",
        "w               w",
        "w               wwww",
        "w     w w       w  w",
        "w     www       w  w",
        "w     www          w",
        "w               wwww",
        "w              ww",
        "w              ww",
        "whhw  w        ww",
        "wwww11wwwwwwwwwww",
    ],
    [ /* Level 1 data */
        "                            ",
        "                            ",
        "                            ",
        "                            ",
        "                            ",
        "wwwwwwwww1wwww2wwwwwwwwwwwww",
        " 5                         w",
        " 5                         w",
        " 5                         w",
        " 5                         w",
        " 5                         w",
        "wwwwwwwwwwwwwwwwwwwwwwwwwwww",
    ],
    [
        "                 ",
        "                 ",
        "                 ",
        "wwwwwhwwwwwwwwwwww",
        "whhhh        hhhw",
        "w               w",
        "w               wwww",
        "ww     ww       w  w",
        "ww     ww   ww  w  w",
        "ww     ww          w",
        "w               wwww",
        "w           wwwww",
        "www         wwwww",
        "wwww  w     wwwww",
        "wwww22wwwwwwwwwww",
    ], [], [], // Placeholder for levels 2, 3, 4
    [ /* Level 5 data */
        "                ",
        "                ",
        "                ",
        "                ",
        "   wwwwwwwwwwwww",
        "   ww        hhw",
        "   w           w",
        "   w           w",
        "   wwww     wwww",
        "   wwww     wwww",
        "   w  b     d  w",
        "   w           wwww",
        "   w     w         5",
        "   w    www        5",
        "   w   wwwww       5",
        "   w    www        5",
        "   w     w         5",
        "   w           wwww",
        "   w           w   ",
        "   wwwwwwwwwwwww",
    ],
];